version: '3.8'

services:
  # Notre service de base de donn√©es
  db:
    image: postgres:latest
    container_name: ma-base-auto
    environment:
      POSTGRES_PASSWORD: rft3055
    # ports:
    #   - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: mon-app-flask
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy